// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: shipping/shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_shipping_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type EstimateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateRequest) Reset() {
	*x = EstimateRequest{}
	mi := &file_shipping_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateRequest) ProtoMessage() {}

func (x *EstimateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateRequest.ProtoReflect.Descriptor instead.
func (*EstimateRequest) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *EstimateRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *EstimateRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type EstimateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EstimatedDays int32                  `protobuf:"varint,1,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateResponse) Reset() {
	*x = EstimateResponse{}
	mi := &file_shipping_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateResponse) ProtoMessage() {}

func (x *EstimateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateResponse.ProtoReflect.Descriptor instead.
func (*EstimateResponse) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *EstimateResponse) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

var File_shipping_shipping_proto protoreflect.FileDescriptor

const file_shipping_shipping_proto_rawDesc = "" +
	"\n" +
	"\x17shipping/shipping.proto\"E\n" +
	"\x04Item\x12!\n" +
	"\fproduct_code\x18\x01 \x01(\tR\vproductCode\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"I\n" +
	"\x0fEstimateRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x1b\n" +
	"\x05items\x18\x02 \x03(\v2\x05.ItemR\x05items\"9\n" +
	"\x10EstimateResponse\x12%\n" +
	"\x0eestimated_days\x18\x01 \x01(\x05R\restimatedDays2=\n" +
	"\bShipping\x121\n" +
	"\bEstimate\x12\x10.EstimateRequest\x1a\x11.EstimateResponse\"\x00B:Z8github.com/Laviniarm/microservices-proto/golang/shippingb\x06proto3"

var (
	file_shipping_shipping_proto_rawDescOnce sync.Once
	file_shipping_shipping_proto_rawDescData []byte
)

func file_shipping_shipping_proto_rawDescGZIP() []byte {
	file_shipping_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_shipping_proto_rawDesc), len(file_shipping_shipping_proto_rawDesc)))
	})
	return file_shipping_shipping_proto_rawDescData
}

var file_shipping_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shipping_shipping_proto_goTypes = []any{
	(*Item)(nil),             // 0: Item
	(*EstimateRequest)(nil),  // 1: EstimateRequest
	(*EstimateResponse)(nil), // 2: EstimateResponse
}
var file_shipping_shipping_proto_depIdxs = []int32{
	0, // 0: EstimateRequest.items:type_name -> Item
	1, // 1: Shipping.Estimate:input_type -> EstimateRequest
	2, // 2: Shipping.Estimate:output_type -> EstimateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shipping_shipping_proto_init() }
func file_shipping_shipping_proto_init() {
	if File_shipping_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_shipping_proto_rawDesc), len(file_shipping_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_shipping_proto_msgTypes,
	}.Build()
	File_shipping_shipping_proto = out.File
	file_shipping_shipping_proto_goTypes = nil
	file_shipping_shipping_proto_depIdxs = nil
}
